### ISSUE TITLE
HDF5 Reading -- Fails when using station='*'

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#64]
I have been using the `rfdbget_data()` method. The docs state that you can use the `station='*'` wildcard. But it always fails.

I pasted my current work around for station by station reading  below, but that should be a temporary solution.

Is this possibly an artifact of having a single station in an `h5` file? 

```python
import os.path as p 
from glob import glob
from pyglimer.rf import RFStream
from pyglimer.database.rfh5 import RFDataBase


def readrf_h5network(database, network="YP", phase='P', pol='v'):

    # Glob the RF directory
    files_to_try_to_read = glob(p.join(
        database, 'waveforms', 'RF', 'P', f'{network}.*.h5'
        )
    )

    # Start with empty stream
    st = RFStream()

    # Read files into directory:
    for _file in files_to_try_to_read:

        with RFDataBase(_file) as rfdb:
            station = p.basename(_file).split('.')[1]
            
            try:
                # Do define station
                x = rfdb.get_data(
                    network='YP', station=station,
                    phase=phase, pol=pol,
                    evt_time='*')
                
                # Add station stream to complete steam.
                st += x

            except Exception as e:

                print(f'{network}.{station}: ', e)

    return st

```

**Comment by PeterMakus** [comment]
Could you send me the script that actually failed for you? Because, again, it works flawlessly for me.
Note that with the current implementation, you can only wildcard the file path _end to the front in the hierachy_
``hierarchy = "/{tag}/{network}/{station}/{phase}/{pol}/{evt_time}"``

Hence, you can always wildcard `evt_time`, but if you want to wildcard `phase`, you will also have to put `pol='*'`. But, to be honest, I just don't see why anyone would want to wildcard another parameter but the time, so I might just change the docs, so they just say that `evt_time` allows for wildcards.

Let me know if this solves your issue.

**Comment by PeterMakus** [comment]
I think I will actually hardcode it so that it handles this automatically
